### ISSUE TITLE
Tour of Restate Python Example isn't available via restate-cli 1.1.0

### ISSUE THREAD

**Issue by aleury** [restatedev/examples#195]
Using the latest release of the restate cli tool, I was attempting to follow the documentation for the "Tour of Restate" example for Python at https://docs.restate.dev/get_started/tour, however I'm seeing an error when I run the following from step 1 of the tutorial:

```sh
restate example python-tour-of-restate && cd python-tour-of-restate
```
which outputs

```sh
Error: Unknown example python-tour-of-restate. Use `restate example` to navigate the list of examples.
```
Running `restate example` and selecting "Python" also doesn't show an option for the "tour of restate" example.

I looked around the repo and noticed that there isn't a line for `python-tour-of-restate` in https://github.com/restatedev/examples/blob/main/.tools/prepare_release_zip.sh#L33-L35 so maybe that's related?

**Comment by gvdongen** [comment]
Thank you for letting us know, we will fix it immediately

**Comment by gvdongen** [comment]
Hi, I fixed it, you should now be able to see it.
