### ISSUE TITLE
Generate getting started template Java as zip

### ISSUE THREAD

**Issue by gvdongen** [restatedev/examples#40]
We need a getting started Java template. We can use the `examples/jvm/java-blocking-http` template for this.

To get started a user would need to clone only the `examples/jvm/java-blocking-http` directory. With git sparse checkout this is possible but it quite verbose (4 commands) and is still evolving so it will depend on the git version a user has....

Instead, we could generate a zip file of this template on each release, that can be downloaded with wget and extracted locally.

**Comment by slinkydeveloper** [comment]
Done
