### ISSUE TITLE
Add hello world example typescript in http

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/examples#59]
Like the lambda example, but on http. This to be consistent with Java/Kotlin which both have lamba and http

**Comment by gvdongen** [comment]
You get that from cloning the template. Not sure if there is added value in also adding it to the examples?

**Comment by slinkydeveloper** [comment]
I think we should move those examples in this repo, such that the typescript codegen will then only need to download the zip, like the restate cli: https://github.com/restatedev/restate/blob/main/cli/src/commands/examples.rs

It's beneficial to have simple examples in this repo, to be a single stop for people looking for examples.

**Comment by slinkydeveloper** [comment]
I think we can close this @gvdongen ?
